name: Submodule Publishing
on:
  workflow_dispatch:
    inputs:
      submodule:
        description: 'Submodule to publish (Please make sure to use values defined in the settings.gradle.kts! Example: fabricated-forge-datagen)'
        required: true
jobs:
  release:
    strategy:
      matrix:
        # Use these Java versions
        java: [17]
        # and run on both Linux and Windows
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: echo "./gradlew :$SUBMODULE:build :$SUBMODULE:publish --stacktrace" | bash
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_PUBLISH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PUBLISH_TOKEN }}
          SUBMODULE: ${{ inputs.submodule }}
          GITHUB_RELEASE: true
      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./*/build/libs/
